<?php

declare(strict_types=1);

namespace Spinx\Database\Schema;

use Doctrine\DBAL\Connection;

/**
 * Offline schema introspector — run once at deploy/build time, not per request.
 *
 * Uses Doctrine DBAL 4.x's AbstractSchemaManager::introspectTables() to
 * read the database schema and writes a plain PHP `return [...]` file that
 * SchemaCache::boot() loads into OpCache at worker startup.
 *
 * DBAL 4 API used (verified against official Doctrine documentation):
 *   - $connection->createSchemaManager()              — preferred over deprecated getSchemaManager()
 *   - $schemaManager->introspectTables()              — returns Table[] for all tables
 *   - $table->getObjectName()->toString()             — returns table name as string (DBAL 4 identifier object)
 *   - $table->getColumns()                            — returns Column[] for the table
 *   - $column->getObjectName()->toString()            — returns column name as string (DBAL 4 identifier object)
 *
 * Run via:
 *   php spinx schema:compile
 *
 * Output:
 *   storage/cache/schema_columns.php — a PHP file returning:
 *   ['orders' => ['id','customer_id','total','created_at','updated_at'], ...]
 *
 * Worker reload picks this up automatically on the next boot cycle
 * (RoadRunner's `rr workers --stop-timeout=30` or Swoole's graceful restart).
 */
final class SchemaCompiler
{
    public function __construct(
        private readonly Connection $connection,
        private readonly string     $outputPath,
    ) {
    }

    /**
     * Introspects all tables via DBAL and writes the column map to $outputPath.
     *
     * @throws \RuntimeException If the output directory cannot be created or the file cannot be written.
     */
    public function compile(): void
    {
        $outputDir = dirname($this->outputPath);

        if (!is_dir($outputDir) && !mkdir($outputDir, 0755, true) && !is_dir($outputDir)) {
            throw new \RuntimeException("Cannot create schema cache directory: {$outputDir}");
        }

        $map = $this->buildColumnMap();

        $export   = var_export($map, true);
        $contents = "<?php\n\n// Auto-generated by `spinx schema:compile` — do not edit manually.\n// Re-run the command after any migration that adds or removes columns.\n\nreturn {$export};\n";

        if (file_put_contents($this->outputPath, $contents) === false) {
            throw new \RuntimeException("Cannot write schema cache to: {$this->outputPath}");
        }
    }

    /**
     * Returns how many tables were discovered in the last compile() call.
     * Only meaningful immediately after calling compile() — not persisted.
     *
     * @return array<string, string[]>
     */
    public function buildColumnMap(): array
    {
        $schemaManager = $this->connection->createSchemaManager();

        /** @var \Doctrine\DBAL\Schema\Table[] $tables */
        $tables = $schemaManager->introspectTables();

        $map = [];

        foreach ($tables as $table) {
            $tableName = $table->getObjectName()->toString();
            $columnNames = [];

            foreach ($table->getColumns() as $column) {
                $columnNames[] = $column->getObjectName()->toString();
            }

            $map[$tableName] = $columnNames;
        }

        // Sort table names for deterministic output (easier to diff after migrations)
        ksort($map);

        return $map;
    }
}
