<?php

declare(strict_types=1);

namespace Spinx\Kernel;

use Spinx\Container\ContainerFactory;
use Spinx\Http\Middleware\Pipeline;
use Spinx\Routing\ModuleLoader;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Symfony\Component\Routing\Matcher\UrlMatcher;
use Symfony\Component\Routing\RequestContext;
use Symfony\Component\Routing\RouteCollection;
use Symfony\Component\Routing\Exception\ResourceNotFoundException;

/**
 * Boots exactly once per process. Every ServerAdapter
 * calls boot() a single time at process start, then reuses this same
 * Kernel instance for the lifetime of the process — this is what gives
 * Spinx its speed advantage over a traditional per-request PHP bootstrap.
 */
final class Kernel
{
    public const VERSION = '1.0.21';

    private ContainerInterface $container;
    private RouteCollection $routes;
    private RequestScope $requestScope;
    private bool $booted = false;

    public function __construct(
        private readonly string $projectRoot,
        private readonly bool $debug = false,
    ) {
        if (!defined('SPINX_BASE_PATH')) {
            define('SPINX_BASE_PATH', $this->projectRoot);
        }
    }

    public function boot(): void
    {
        if ($this->booted) {
            return;
        }

        $this->loadEnvironment();

        \Spinx\Support\Config::boot($this->projectRoot . '/config');

        $this->container = (new ContainerFactory($this->projectRoot, $this->debug))->build();

        // Model is an active-record base class, so it needs a connection
        // available via a static resolver rather than constructor
        // injection — wired once here, at boot, not
        // per-request.
        if ($this->container->has(\Spinx\Database\Connection\ConnectionManager::class)) {
            $manager = $this->container->get(\Spinx\Database\Connection\ConnectionManager::class);

            \Spinx\Database\Model::setConnectionManager($manager);
            \Spinx\Database\DB::setConnectionManager($manager);
        }

        // Boot the pre-compiled schema column cache — zero DB calls,
        // reads from storage/cache/schema_columns.php (generated by
        // `spinx schema:compile`). Called after the connection is wired
        // because SchemaCache::boot() itself is purely file I/O and needs
        // no database connection, but ordering it here keeps the boot
        // sequence deterministic: env → config → DI → db → schema → routes.
        \Spinx\Database\Schema\SchemaCache::boot($this->projectRoot);

        // Boot Auth & Session subsystems
        if ($this->container->has(\Spinx\Session\SessionInterface::class)) {
            $session = $this->container->get(\Spinx\Session\SessionInterface::class);
            $authModel = (string) \Spinx\Support\Config::get('auth.model', 'App\\Modules\\Users\\Infrastructure\\Persistence\\Models\\User');
            $passwordField = (string) \Spinx\Support\Config::get('auth.password_field', 'password');
            $provider = new \Spinx\Auth\EloquentUserProvider($authModel, $passwordField);
            \Spinx\Auth\Auth::boot($provider, $session);
        }

        // Boot Logging subsystem
        if ($this->container->has(\Spinx\Log\LogManager::class)) {
            \Spinx\Log\Log::setManager($this->container->get(\Spinx\Log\LogManager::class));
        }

        // Boot View Facade
        if ($this->container->has(\Spinx\Templating\TemplateRenderer::class)) {
            \Spinx\Templating\View::setRenderer($this->container->get(\Spinx\Templating\TemplateRenderer::class));
        }

        // Boot Redis subsystem
        if ($this->container->has(\Spinx\Redis\RedisManager::class)) {
            \Spinx\Redis\Redis::setManager($this->container->get(\Spinx\Redis\RedisManager::class));
        }

        // Boot Cache subsystem
        if ($this->container->has(\Spinx\Cache\CacheManager::class)) {
            \Spinx\Cache\Cache::setManager($this->container->get(\Spinx\Cache\CacheManager::class));
        }

        // Boot Queue subsystem
        if ($this->container->has(\Spinx\Queue\QueueManager::class)) {
            \Spinx\Queue\Queue::setManager($this->container->get(\Spinx\Queue\QueueManager::class));
        }

        // Boot Broadcasting subsystem
        if ($this->container->has(\Spinx\Broadcasting\BroadcastManager::class)) {
            \Spinx\Broadcasting\Broadcast::setManager($this->container->get(\Spinx\Broadcasting\BroadcastManager::class));
        }

        // Boot Filesystem & Storage subsystem
        if ($this->container->has(\Spinx\Filesystem\FilesystemManager::class)) {
            \Spinx\Filesystem\Storage::setManager($this->container->get(\Spinx\Filesystem\FilesystemManager::class));
        }

        // Boot Vector search subsystem
        if ($this->container->has(\Spinx\Database\Vector\VectorService::class)) {
            \Spinx\Database\Vector\Vector::setService($this->container->get(\Spinx\Database\Vector\VectorService::class));
        }

        // Boot Application LLM subsystem
        if ($this->container->has(\Spinx\Llm\LlmManager::class)) {
            \Spinx\Llm\Llm::setManager($this->container->get(\Spinx\Llm\LlmManager::class));
        }

        // Boot AI Framework Builder
        if ($this->container->has(\Spinx\Ai\AiManager::class)) {
            \Spinx\Ai\Ai::setManager($this->container->get(\Spinx\Ai\AiManager::class));
        }

        $this->routes = $this->compileRoutes();
        $this->requestScope = new RequestScope(
            $this->container,
            $this->container->hasParameter('spinx.request_scoped_service_ids')
                ? $this->container->getParameter('spinx.request_scoped_service_ids')
                : []
        );

        $this->booted = true;
    }

    /**
     * Loads .env into $_ENV/$_SERVER/getenv() once, at boot — cheap even
     * on a persistent process since it only runs once per worker
     * lifetime, not per request. Real environment variables already set
     * by the OS or a container orchestrator (Docker, Kubernetes) always
     * win — Dotenv::createImmutable() never overwrites an existing
     * variable, which is exactly the right behavior for production
     * deploys that set real env vars instead of shipping a .env file.
     */
    private function loadEnvironment(): void
    {
        if (!is_file($this->projectRoot . '/.env')) {
            return; // No .env — fine, real env vars or config defaults carry the app.
        }

        \Dotenv\Dotenv::createImmutable($this->projectRoot)->load();
    }

    /**
     * Dispatches a single Symfony Request through the compiled route table
     * and returns a Symfony Response. Called by the active ServerAdapter
     * for every inbound request.
     */
    public function handle(Request $request): Response
    {
        if (!$this->booted) {
            throw new \LogicException('Kernel::boot() must be called before handle().');
        }

        \Spinx\Http\Request::setCurrentRequest($request);

        // Reset request-scoped services FIRST, before any application code
        // runs, so nothing from a previous request on this worker/coroutine
        // can leak forward. This is the enforcement point for §4 of the
        // build spec.
        $this->requestScope->reset();

        $dispatch = function (Request $req): Response {
            $context = new RequestContext();
            $context->fromRequest($req);
            $matcher = new UrlMatcher($this->routes, $context);

            try {
                $parameters = $matcher->match($req->getPathInfo());
            } catch (ResourceNotFoundException) {
                return new Response('Not Found', 404);
            } catch (\Symfony\Component\Routing\Exception\MethodNotAllowedException $e) {
                if ($req->getMethod() === 'OPTIONS') {
                    return new Response('', 204);
                }
                return new Response('Method Not Allowed', 405);
            }

            $controller = $parameters['_controller'] ?? null;
            $middlewareClasses = $parameters['_middleware'] ?? [];
            unset($parameters['_controller'], $parameters['_route'], $parameters['_middleware']);

            if ($controller === null) {
                return new Response('Route has no controller bound.', 500);
            }

            $resolved = $this->resolveController($controller);
            $finalHandler = fn (Request $r): Response => $resolved($r, ...array_values($parameters));

            $response = (new Pipeline($this->container))->handle($req, $middlewareClasses, $finalHandler);

            if (!$response instanceof Response) {
                throw new \LogicException(sprintf(
                    'Controller for route "%s" must return a Symfony Response, got %s.',
                    $req->getPathInfo(),
                    get_debug_type($response)
                ));
            }

            return $response;
        };

        try {
            $corsMiddleware = new \Spinx\Http\Middleware\CorsMiddleware();
            $runner = fn (Request $r): Response => $corsMiddleware->process($r, $dispatch);

            if ($this->container->has(\Spinx\Session\SessionInterface::class)) {
                $session = $this->container->get(\Spinx\Session\SessionInterface::class);
                $sessionMiddleware = new \Spinx\Session\SessionMiddleware($session);

                return $sessionMiddleware->process($request, $runner);
            }

            return $runner($request);
        } catch (\Throwable $e) {
            $response = $this->handleException($e, $request);
            $corsMiddleware = new \Spinx\Http\Middleware\CorsMiddleware();
            return $corsMiddleware->process($request, fn (): Response => $response);
        } finally {
            // Guarantee zero cross-request memory leak in persistent workers
            \Spinx\Http\Request::setCurrentRequest(null);
            \Spinx\Security\Csrf::reset();
            \Spinx\Auth\Auth::resetApiState();
            $this->requestScope->reset();
        }

    }

    private function handleException(\Throwable $e, Request $request): Response
    {
        $isJson = $request->isXmlHttpRequest()
            || str_contains((string) $request->headers->get('Accept', ''), 'application/json')
            || str_contains((string) $request->headers->get('Content-Type', ''), 'application/json')
            || str_starts_with($request->getPathInfo(), '/api/');

        if ($e instanceof \Spinx\Validation\ValidationException) {
            return new Response(
                (string) json_encode([
                    'message' => 'The given data was invalid.',
                    'errors'  => $e->errors(),
                ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES),
                422,
                ['Content-Type' => 'application/json']
            );
        }

        \Spinx\Log\Log::error($e->getMessage(), [
            'exception' => $e,
            'method'    => $request->getMethod(),
            'uri'       => $request->getRequestUri(),
            'ip'        => $request->getClientIp(),
        ]);

        if ($isJson) {
            $payload = [
                'error'   => 'Server Error',
                'message' => $this->debug ? $e->getMessage() : 'An internal error occurred.',
            ];
            if ($this->debug) {
                $payload['file'] = $e->getFile() . ':' . $e->getLine();
            }

            return new Response(
                (string) json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES),
                500,
                ['Content-Type' => 'application/json']
            );
        }

        if ($this->debug) {
            $msg = sprintf(
                "<h1>500 Internal Server Error</h1><p><strong>%s:</strong> %s</p><p>in <code>%s:%d</code></p><pre>%s</pre>",
                htmlspecialchars(get_class($e)),
                htmlspecialchars($e->getMessage()),
                htmlspecialchars($e->getFile()),
                $e->getLine(),
                htmlspecialchars($e->getTraceAsString())
            );

            return new Response($msg, 500, ['Content-Type' => 'text/html']);
        }

        return new Response('500 Internal Server Error', 500);
    }


    public function shutdown(): void
    {
        $this->booted = false;
    }

    public function getContainer(): ContainerInterface
    {
        return $this->container;
    }

    public function getRequestScope(): RequestScope
    {
        return $this->requestScope;
    }

    private function compileRoutes(): RouteCollection
    {
        $routes = new RouteCollection();
        (new ModuleLoader($this->projectRoot))->loadRoutes($routes);

        // Built-in System Routes: Spinx AI Builder Web Dashboard (Local / Development only)
        $aiEnabled = env('SPINX_AI_DASHBOARD_ENABLED', false) || env('APP_ENV', 'local') !== 'production';
        if ($aiEnabled) {
            $routes->add('__spinx_ai_dashboard', new \Symfony\Component\Routing\Route('/_spinx/ai', [
                '_controller' => [\Spinx\Ai\Web\AiDashboardController::class, 'index'],
            ], [], [], '', [], ['GET']));

            $routes->add('__spinx_ai_build', new \Symfony\Component\Routing\Route('/_spinx/ai/build', [
                '_controller' => [\Spinx\Ai\Web\AiDashboardController::class, 'build'],
            ], [], [], '', [], ['POST']));

            $routes->add('__spinx_ai_reason', new \Symfony\Component\Routing\Route('/_spinx/ai/reason', [
                '_controller' => [\Spinx\Ai\Web\AiDashboardController::class, 'reason'],
            ], [], [], '', [], ['POST']));

            $routes->add('__spinx_ai_context', new \Symfony\Component\Routing\Route('/_spinx/ai/context', [
                '_controller' => [\Spinx\Ai\Web\AiDashboardController::class, 'context'],
            ], [], [], '', [], ['GET']));
        }

        // Built-in System Routes: Real-Time Broadcasting Authentication
        $routes->add('__spinx_broadcasting_auth', new \Symfony\Component\Routing\Route('/_spinx/broadcasting/auth', [
            '_controller'  => [\Spinx\Broadcasting\BroadcastAuthController::class, 'authenticate'],
            '_csrf_exempt' => true,
        ], [], [], '', [], ['POST']));

        return $routes;
    }

    private function resolveController(mixed $controller): callable
    {
        if (is_callable($controller)) {
            return $controller;
        }

        // Support "ControllerClass@method" syntax
        if (is_string($controller) && str_contains($controller, '@')) {
            [$class, $method] = explode('@', $controller, 2);
            $instance = $this->container->has($class) ? $this->container->get($class) : (class_exists($class) ? new $class() : null);

            if ($instance !== null && method_exists($instance, $method)) {
                return [$instance, $method];
            }

            throw new \RuntimeException(sprintf(
                'Method "%s" does not exist on controller "%s".',
                $method,
                $class
            ));
        }

        // Support [ControllerClass, 'method'] syntax
        if (is_array($controller) && count($controller) === 2) {
            [$class, $method] = $controller;
            $instance = is_object($class) ? $class : ($this->container->has($class) ? $this->container->get($class) : (class_exists((string) $class) ? new $class() : null));

            if ($instance !== null && method_exists($instance, (string) $method)) {
                return [$instance, (string) $method];
            }
        }

        if (is_string($controller)) {
            $instance = $this->container->has($controller) ? $this->container->get($controller) : (class_exists($controller) ? new $controller() : null);

            if ($instance !== null) {
                if (is_callable($instance) || method_exists($instance, '__invoke')) {
                    return $instance;
                }
            }
        }

        throw new \RuntimeException(sprintf(
            'Controller "%s" could not be resolved. Controllers must be callable or define an action method and be registered in the container via module.php.',
            is_string($controller) ? $controller : get_debug_type($controller)
        ));
    }
}
