name: SpinxShell
options:
  bundleIdPrefix: africa.spinx
  deploymentTarget:
    iOS: "15.0"

targets:
  SpinxShell:
    type: application
    platform: iOS
    sources:
      - SpinxShell
    info:
      path: SpinxShell/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: africa.spinx.shell
        SWIFT_VERSION: "5.0"
